export const palette = {
  dark: {
    accent: '#00d9ff',
    background: '#120b1e',
    border: 'rgba(112, 72, 140, 0.4)',
    card: '#1a102a',
    danger: '#ff2e63',
    muted: '#bfa8d6',
    pink: '#ff2e97',
    surface: '#1e1330',
    text: '#e8dff5',
  },
  light: {
    accent: '#00b4d4',
    background: '#f6ebff',
    border: 'rgba(112, 72, 140, 0.35)',
    card: '#fdf7ff',
    danger: '#d91465',
    muted: '#5b4276',
    pink: '#ff3fa4',
    surface: '#f2ddff',
    text: '#2a1840',
  },
  terminal: {
    accent: '#71f5ad',
    background: '#010705',
    border: '#55ffad',
    card: '#010c08',
    danger: '#ff718e',
    muted: '#a6ffd0',
    pink: '#71f5ad',
    surface: '#03150d',
    text: '#dffff0',
  },
} as const;

export const terminalThemeVariables = {
  '--color-accent': palette.terminal.accent,
  '--color-error': palette.terminal.danger,
  '--color-mobile-background': palette.terminal.background,
  '--color-mobile-border': palette.terminal.border,
  '--color-mobile-card': palette.terminal.card,
  '--color-mobile-dark-background': palette.terminal.background,
  '--color-mobile-dark-border': palette.terminal.border,
  '--color-mobile-dark-card': palette.terminal.card,
  '--color-mobile-dark-muted': palette.terminal.muted,
  '--color-mobile-dark-surface': palette.terminal.surface,
  '--color-mobile-dark-text': palette.terminal.text,
  '--color-mobile-muted': palette.terminal.muted,
  '--color-mobile-surface': palette.terminal.surface,
  '--color-mobile-text': palette.terminal.text,
  '--color-native-background': palette.terminal.background,
  '--color-native-border': palette.terminal.border,
  '--color-native-card': palette.terminal.card,
  '--color-native-dark-background': palette.terminal.background,
  '--color-native-dark-border': palette.terminal.border,
  '--color-native-dark-card': palette.terminal.card,
  '--color-native-dark-muted': palette.terminal.muted,
  '--color-native-dark-surface': palette.terminal.surface,
  '--color-native-dark-text': palette.terminal.text,
  '--color-native-muted': palette.terminal.muted,
  '--color-native-surface': palette.terminal.surface,
  '--color-native-text': palette.terminal.text,
  '--color-primary': palette.terminal.pink,
  '--color-success': palette.terminal.accent,
} as const;
