"""Regenerate web font subsets with fonttools[woff]. Native fonts are unchanged."""

from pathlib import Path
from fontTools import subset
from fontTools.ttLib import TTFont

root = Path(__file__).resolve().parents[1]
fonts = root / "packages/ui/src/shared/assets/fonts"
latin = set(range(0x250)) | set(range(0x2000, 0x2070))
faces = []

for weight, name in [(400, "Regular"), (700, "Bold")]:
    source = fonts / f"MSW98UI-{name}.woff2"
    coverage = set(TTFont(source).getBestCmap())
    groups = [("latin", coverage & latin), ("other", coverage - latin)]
    for group, codepoints in groups:
        font = TTFont(source, recalcTimestamp=False)
        options = subset.Options()
        options.recalc_timestamp = False
        subsetter = subset.Subsetter(options=options)
        subsetter.populate(unicodes=codepoints)
        subsetter.subset(font)
        filename = f"MSW98UI-{name}-{group}.woff2"
        font.save(fonts / filename)
        # Exact coverage avoids downloading a fallback for unsupported glyphs.
        ranges = []
        for point in sorted(codepoints):
            if ranges and point == ranges[-1][1] + 1:
                ranges[-1][1] = point
            else:
                ranges.append([point, point])
        unicode_range = ", ".join(
            f"U+{start:X}-{end:X}" if start != end else f"U+{start:X}"
            for start, end in ranges
        )
        faces.append(f'''@font-face {{
  font-family: "MSW98UI";
  font-style: normal;
  font-weight: {weight};
  font-display: swap;
  src: url("../ui/src/shared/assets/fonts/{filename}") format("woff2");
  unicode-range: {unicode_range};
}}''')

(root / "packages/tailwind/fonts.css").write_text(
    "/* Generated by scripts/subset-web-fonts.py. */\n" + "\n\n".join(faces) + "\n"
)
